
#Common config settings
[common]
	#If this is enable and Biomes O' Plenty are played with, the crafting recipe for the Terrestrial Artifact can use SurvivalPlus's ruby, topaz, and sapphire. By default this is set to true as the idea of the Terrestrial Artifact is that you need to go to all BOP biomes to find the needed gems, whereas SurvivalPlus gems generate everywhere.
	enableReplaceBOPRecipe = false
	#Disable SurvivalPlus Copper Ore Gen
	disableCopperOreGen = true
	#Disable SurvivalPlus Tin Ore Gen
	disableTinOreGen = true
	#Disable SurvivalPlus Titanium Ore Gen
	disableTitaniumOreGen = true
	#Disable SurvivalPlus Amethyst Gen
	disableAmethystGen = true
	#Disable SurvivalPlus Ruby Gen
	disableRubyGen = true
	#Disable SurvivalPlus Topaz Gen
	disableTopazGen = true
	#Disable SurvivalPlus Sapphire Gen
	disableSapphireGen = true
	#Disable SurvivalPlus Pearl Gen
	disablePearlGen = true
	#Disable SurvivalPlus Spinel Gen
	disableSpinelGen = true
	#If this is set to 0 anyone can use the Wak Command. If set above 4 then it will return 4.
	#Range: 0 ~ 4
	opWak = 0
	#Disable SurvivalPlus Update Checker Message
	disableUpdateCheck = true
	#Disable Sounds Played Through sun.audio
	disableSunAudio = false
	#Disable SurvivalPlus Thank You Message
	disableThanks = true

